package com.rules

import com.matrixbi.utils.tests.Person

rule "Good Morning"
when
$person: Person(time >= 0, time < 12)
then
$person.setGreet("Good Morning " + $person.getName() );
retract( $person )
end

rule "Good Afternoon"
when
$person: Person(time >= 12, time < 16)
then
$person.setGreet("Good Afternoon " + $person.getName() );
retract( $person )

end

rule "Good Night"
when
$person: Person(time >= 16, time <= 24)
then
$person.setGreet("Good Night8 " + $person.getName() );
retract( $person )
end
